# Generated by Django 2.0.1 on 2018-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
