# Generated by Django 2.0.1 on 2018-01-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180126_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mbc_parent_id',
            field=models.ForeignKey(blank=True, db_column='mbc_parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Category', verbose_name='Parent Category ID'),
        ),
    ]
