# Generated by Django 2.0.1 on 2018-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180126_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mbc_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Category ID'),
        ),
    ]
