# Generated by Django 2.0.1 on 2018-01-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20180127_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mbc_parent_id',
            field=models.ForeignKey(db_column='mbc_parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='db.Category', verbose_name='Parent Category ID'),
        ),
    ]
