# Generated by Django 2.0.1 on 2018-01-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20180128_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_static',
            name='mbp_s_pid',
            field=models.OneToOneField(db_column='mbp_s_pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.Post', verbose_name='Post ID'),
        ),
    ]
