# Generated by Django 2.0.1 on 2018-01-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20180128_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tag',
            name='mbp_t_pid',
            field=models.ForeignKey(db_column='mbp_t_pid', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='db.Post', verbose_name='Post ID'),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='mbp_t_tid',
            field=models.ForeignKey(db_column='mbp_t_tid', on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='db.Tag', verbose_name='Tag ID'),
        ),
    ]
