# Generated by Django 2.0.1 on 2018-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20180128_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mbp_image_caption',
            field=models.CharField(default='', max_length=16, verbose_name='Image Caption'),
        ),
    ]
