# Generated by Django 2.0.1 on 2018-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_post_mbp_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='mbt_colormark',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
