# Generated by Django 2.0.1 on 2018-03-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_tag_mbt_colormark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together={('username', 'email')},
        ),
    ]
