# Generated by Django 2.0.1 on 2018-03-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20180328_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set(),
        ),
    ]
