# Generated by Django 2.0.1 on 2018-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20180328_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mbu_email',
            field=models.EmailField(default='demo@local.com', error_messages={'unique': 'The email address has been registered by another user.'}, help_text='Required. 100 characters or fewer. follow in with standard email format.', max_length=100, unique=True, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
