# Generated by Django 2.0.1 on 2018-01-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20180119_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='dept',
            field=models.CharField(default='IT', max_length=100),
        ),
    ]
