# Generated by Django 2.0.1 on 2018-01-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_myuser_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
